homeassistant:
  # Name of the location where Home Assistant is running
  name: Swistackiego
  # Location required to calculate the time the sun rises and sets
  latitude: 51.1062
  longitude: 17.04070
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 119
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt_login
  password: !secret mqtt_password
  port: 19470


light:
  - platform: mqtt
    name: "Wejscie"
    state_topic: "home/lights/18/6/state"
    command_topic: "home/lights/18/6/switch"
  - platform: mqtt
    name: "Lustro lazienka"
    state_topic: "home/lights/19/5/state"
    command_topic: "home/lights/19/5/switch"
  - platform: mqtt
    name: "Lazienka"
    state_topic: "home/lights/18/4/state"
    command_topic: "home/lights/18/4/switch"
  - platform: mqtt
    name: "Kuchnia"
    state_topic: "home/lights/18/3/state"
    command_topic: "home/lights/18/3/switch"
  - platform: mqtt
    name: "Salon"
    state_topic: "home/lights/18/5/state"
    command_topic: "home/lights/18/5/switch"
  - platform: mqtt
    name: "Sypialnia"
    state_topic: "home/lights/18/1/state"
    command_topic: "home/lights/18/1/switch"
  - platform: mqtt
    name: "Blat kuchnia"
    state_topic: "home/lights/19/4/state"
    command_topic: "home/lights/19/4/switch"

binary_sensor:
  - platform: mqtt
    name: "Master switch"
    state_topic: "home/lights/0/0/state"

group: !include groups.yaml
automation: !include automations.yaml

